"""
Authentication settings (local defaults with env overrides).
"""
import os

SESSION_COOKIE_NAME = os.getenv("MYCASA_SESSION_COOKIE", "mycasa_session")
SESSION_TTL_DAYS = int(os.getenv("MYCASA_SESSION_TTL_DAYS", "30"))
SESSION_COOKIE_SAMESITE = os.getenv("MYCASA_SESSION_SAMESITE", "lax")
SESSION_COOKIE_SECURE = os.getenv("MYCASA_SESSION_SECURE", "0") == "1"

LOCKOUT_MAX_ATTEMPTS = int(os.getenv("MYCASA_LOCKOUT_MAX_ATTEMPTS", "5"))
LOCKOUT_WINDOW_MINUTES = int(os.getenv("MYCASA_LOCKOUT_WINDOW_MINUTES", "15"))
LOCKOUT_DURATION_MINUTES = int(os.getenv("MYCASA_LOCKOUT_DURATION_MINUTES", "15"))

PASSWORD_RESET_TOKEN_TTL_MINUTES = int(os.getenv("MYCASA_PASSWORD_RESET_TTL_MINUTES", "30"))

ADMIN_DB_WRITE_ENABLED = os.getenv("MYCASA_ADMIN_DB_WRITE_ENABLED", "0") == "1"
